### ISSUE TITLE
Running the code on a spark cluster

### ISSUE THREAD

**Issue by sophia-wright-blue** [asidlo/sparkprophet#1]
Thank you for releasing this code - this repo should be very helpful. You mention that the code can easily be modified to run on a spark cluster and you plan to include these steps in a tutorial write-up.

It'd be very helpful if you could briefly mention the modifications required to run the code on a spark cluster.

Thanks again,

**Comment by asidlo** [comment]
The code itself doesn't require any modifications to run the code on a spark cluster.  The only change you would need to do is to modify the spark-submit command to add the python libraries via --py-files flag and add the --master flag to specify the ip and port for the master node in your cluster. In addition, most applications of this code would be using their own dataset which is often too large to fit on a single machine, so if that is your case then you would need to modify the retrieve_data method to change the load csv spark api to pull from s3 or some other distributed storage.

If you run into any other issues let me know. Like I mentioned in the README, I do plan on also going through the process of running this sample code on a spark cluster and adding the details to the README or some other external writeup, but it may have to wait until the weekend or whenever I get another chunk of spare time.

**Comment by sophia-wright-blue** [comment]
Thank you so much for your reply. I think I'm going to run the code on Databricks - if you could include some details for running this on Databricks in your README or write-up, that'd be very helpful.

Thank you again for making this code available - I look forward to your write-up and to running the code!

**Comment by sophia-wright-blue** [comment]
polite query to @asidlo about the tutorial write-up mentioned in the README and in the response above. thanks,

**Comment by asidlo** [comment]
I know it has been a while since I said I would write up a tutorial on the code, but unfortunately, I haven't had a lot of time recently to start it. If you have any specific questions pertaining to the code, open another issue, as I am more likely to respond to those in a timely manner. As for the tutorial, I do not foresee myself having time in the near future, but I will do my best.

**Comment by sophia-wright-blue** [comment]
thanks for replying @asidlo i'll open an issue on a specific topic.
